In [1]:
import numpy as np

In [10]:
rand = np.random.RandomState(20)
x = rand.randint(10, size=20)

In [11]:
x

array([3, 9, 4, 6, 7, 2, 0, 6, 8, 5, 3, 0, 6, 6, 0, 9, 5, 7, 5, 2])

In [12]:
[x[0], x[12]]

[3, 6]

In [13]:
ind = [0, 12]

In [14]:
x[ind]

array([3, 6])

In [15]:
ind1 = np.array([[0, 12],
                [3, 4]])
x[ind1]

array([[3, 6],
       [6, 7]])

In [16]:
y = np.arange(9).reshape((3, 3))

In [17]:
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
y[1, [1, 0, 2]]

array([4, 3, 5])

In [22]:
y[1:, [1, 0, 2]]

array([[4, 3, 5],
       [7, 6, 8]])