In [12]:
import numpy as np

In [13]:
ar=np.array([1,2,3,4])

In [14]:
ar1 = np.concatenate([ar,ar])

In [15]:
ar1

array([1, 2, 3, 4, 1, 2, 3, 4])

In [19]:
ar2 = np.array([[1,2,3], [4,5,6]])

In [20]:
ar3 = np.concatenate([ar2,ar2])
ar3

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [21]:
ar4 = np.concatenate([ar2, ar2], axis=1)

In [105]:
ar4

array([[7, 2, 3, 7, 2, 3],
       [4, 5, 3, 4, 5, 3]])

In [106]:
ar[1:]

array([2, 3, 4])

In [22]:
np.vstack([ar[1:], ar2])

array([[2, 3, 4],
       [1, 2, 3],
       [4, 5, 6]])

In [23]:
ar5=np.hstack([ar4, np.array([[1], [2]])])

In [24]:
ar5

array([[1, 2, 3, 1, 2, 3, 1],
       [4, 5, 6, 4, 5, 6, 2]])

In [25]:
ar6 = np.arange(0,20,3)

In [26]:
a1,a2,a3 = np.split(ar6, [2, 4])

In [27]:
print(a1, a2, a3)

[0 3] [6 9] [12 15 18]


In [28]:
ar6_1, ar6_2 = np.vsplit(ar4, [1])
print("ar6_1 =" ,ar6_1)  
print("ar6_2 =" ,ar6_2) 

ar6_1 = [[1 2 3 1 2 3]]
ar6_2 = [[4 5 6 4 5 6]]


In [29]:
ar6_3, ar6_4 = np.hsplit(ar4, [4])
print("ar6_3 =" ,ar6_3)  
print("ar6_3 =" ,ar6_4) 

ar6_3 = [[1 2 3 1]
 [4 5 6 4]]
ar6_3 = [[2 3]
 [5 6]]


In [30]:
ar5.transpose()

array([[1, 4],
       [2, 5],
       [3, 6],
       [1, 4],
       [2, 5],
       [3, 6],
       [1, 2]])

In [31]:
np.save('exempleTab.numpy',ar6)

In [32]:
ar7 = np.load('exempleTab.numpy.npy')

In [33]:
ar7

array([ 0,  3,  6,  9, 12, 15, 18])