In [1]:
import numpy as np

In [2]:
np.random.seed(42)

produits = np.array(['p1', 'p2', 'p3', 'p4', 'p5'])
regions = np.array(['r1', 'r2', 'r3', 'r4'])

data_ventes = np.random.randint(20, 100, size=(len(regions), len(produits)))

# Affichage des données générées
print("Données de ventes générées:")
print(data_ventes)

Données de ventes générées:
[[71 34 91 80 40]
 [94 94 43 22 41]
 [72 21 49 57 21]
 [83 79 40 52 95]]


In [4]:
import os
from mistralai.client import MistralClient
from mistralai.models.chat_completion import ChatMessage

api_key = 'qAOI4c3dA69nZC5UqKp9IVcMNyt5kY6O'
model = "mistral-large-latest"

client = MistralClient(api_key=api_key)

chat_response = client.chat(
    model=model,
    messages=[ChatMessage(role="user", content=f"""
Voici les données de ventes :
{data_ventes}

Pouvez-vous identifier les ventes maximales et minimales pour chaque région et chaque produit ?
""")]
)

print(chat_response.choices[0].message.content)

Pour identifier les ventes maximales et minimales pour chaque région et chaque produit, nous devons d'abord comprendre la structure des données. Supposons que chaque ligne représente une région et chaque colonne représente un produit. Voici les données de ventes :

```
[[71 34 91 80 40]
 [94 94 43 22 41]
 [72 21 49 57 21]
 [83 79 40 52 95]]
```

### Ventes maximales et minimales pour chaque région

Pour chaque région, nous allons trouver la vente maximale et minimale parmi les produits.

#### Région 1 : [71, 34, 91, 80, 40]
- Maximale : 91
- Minimale : 34

#### Région 2 : [94, 94, 43, 22, 41]
- Maximale : 94
- Minimale : 22

#### Région 3 : [72, 21, 49, 57, 21]
- Maximale : 72
- Minimale : 21

#### Région 4 : [83, 79, 40, 52, 95]
- Maximale : 95
- Minimale : 40

### Ventes maximales et minimales pour chaque produit

Pour chaque produit, nous allons trouver la vente maximale et minimale parmi les régions.

#### Produit 1 : [71, 94, 72, 83]
- Maximale : 94
- Minimale : 71

#### Produit 2